"""
This type stub file was generated by pyright.
"""

import codecs
import io
import os
import random
import sys
from __future__ import unicode_literals
from .options import parseOpts
from .compat import compat_getpass, compat_shlex_split, workaround_optparse_bug9161
from .utils import DEFAULT_OUTTMPL, DateRange, DownloadError, MaxDownloadsReached, SameFileError, decodeOption, expand_path, match_filter_func, preferredencoding, read_batch_urls, render_table, setproctitle, std_headers, write_string
from .update import update_self
from .downloader import FileDownloader
from .extractor import gen_extractors, list_extractors
from .extractor.adobepass import MSO_INFO
from .YoutubeDL import YoutubeDL

__license__ = ...
def main(argv=...):
    ...

__all__ = ['main', 'YoutubeDL', 'gen_extractors', 'list_extractors']
