"""
This type stub file was generated by pyright.
"""

class FileDownloader:
    """File Downloader class.

    File downloader objects are the ones responsible of downloading the
    actual video file and writing it to disk.

    File downloaders accept a lot of parameters. In order not to saturate
    the object constructor with arguments, it receives a dictionary of
    options instead.

    Available options:

    verbose:            Print additional info to stdout.
    quiet:              Do not print messages to stdout.
    ratelimit:          Download speed limit, in bytes/sec.
    retries:            Number of times to retry for HTTP error 5xx
    buffersize:         Size of download buffer in bytes.
    noresizebuffer:     Do not automatically resize the download buffer.
    continuedl:         Try to continue downloads if possible.
    noprogress:         Do not print the progress bar.
    logtostderr:        Log messages to stderr instead of stdout.
    consoletitle:       Display progress in console window's titlebar.
    nopart:             Do not use temporary .part files.
    updatetime:         Use the Last-modified header to set output file timestamps.
    test:               Download only first bytes to test the downloader.
    min_filesize:       Skip files smaller than this size
    max_filesize:       Skip files larger than this size
    xattr_set_filesize: Set ytdl.filesize user xattribute with expected size.
    external_downloader_args:  A list of additional command-line arguments for the
                        external downloader.
    hls_use_mpegts:     Use the mpegts container for HLS videos.
    http_chunk_size:    Size of a chunk for chunk-based HTTP downloading. May be
                        useful for bypassing bandwidth throttling imposed by
                        a webserver (experimental)

    Subclasses of this one must re-define the real_download method.
    """
    _TEST_FILE_SIZE = ...
    params = ...
    def __init__(self, ydl, params) -> None:
        """Create a FileDownloader object with the given options."""
        ...
    
    @staticmethod
    def format_seconds(seconds): # -> LiteralString | Literal['--:--:--']:
        ...
    
    @staticmethod
    def calc_percent(byte_counter, data_len): # -> float | None:
        ...
    
    @staticmethod
    def format_percent(percent): # -> Literal['---.-%']:
        ...
    
    @staticmethod
    def calc_eta(start, now, total, current): # -> int | None:
        ...
    
    @staticmethod
    def format_eta(eta): # -> LiteralString | Literal['--:--', '--:--:--']:
        ...
    
    @staticmethod
    def calc_speed(start, now, bytes): # -> None:
        ...
    
    @staticmethod
    def format_speed(speed): # -> LiteralString | str:
        ...
    
    @staticmethod
    def format_retries(retries): # -> Literal['inf']:
        ...
    
    @staticmethod
    def best_block_size(elapsed_time, bytes): # -> int:
        ...
    
    @staticmethod
    def parse_bytes(bytestr): # -> int | None:
        """Parse a string indicating a byte quantity into an integer."""
        ...
    
    def to_screen(self, *args, **kargs): # -> None:
        ...
    
    def to_stderr(self, message): # -> None:
        ...
    
    def to_console_title(self, message): # -> None:
        ...
    
    def trouble(self, *args, **kargs): # -> None:
        ...
    
    def report_warning(self, *args, **kargs): # -> None:
        ...
    
    def report_error(self, *args, **kargs): # -> None:
        ...
    
    def slow_down(self, start_time, now, byte_counter): # -> None:
        """Sleep if the download speed is over the rate limit."""
        ...
    
    def temp_name(self, filename):
        """Returns a temporary filename for the given filename."""
        ...
    
    def undo_temp_name(self, filename):
        ...
    
    def ytdl_filename(self, filename):
        ...
    
    def try_rename(self, old_filename, new_filename): # -> None:
        ...
    
    def try_utime(self, filename, last_modified_hdr): # -> int | None:
        """Try to set the last-modified time of the given file."""
        ...
    
    def report_destination(self, filename): # -> None:
        """Report destination filename."""
        ...
    
    def report_progress(self, s): # -> None:
        ...
    
    def report_resuming_byte(self, resume_len): # -> None:
        """Report attempt to resume at given byte."""
        ...
    
    def report_retry(self, err, count, retries): # -> None:
        """Report retry in case of HTTP error 5xx"""
        ...
    
    def report_file_already_downloaded(self, file_name): # -> None:
        """Report file has already been fully downloaded."""
        ...
    
    def report_unable_to_resume(self): # -> None:
        """Report it was impossible to resume download."""
        ...
    
    def download(self, filename, info_dict): # -> Literal[True]:
        """Download to a filename using the info from info_dict
        Return True on success and False otherwise
        """
        ...
    
    def real_download(self, filename, info_dict):
        """Real download process. Redefine in subclasses."""
        ...
    
    def add_progress_hook(self, ph): # -> None:
        ...
    


