"""
This type stub file was generated by pyright.
"""

from __future__ import unicode_literals
from .common import FileDownloader
from .f4m import F4mFD
from .hls import HlsFD
from .http import HttpFD
from .rtmp import RtmpFD
from .dash import DashSegmentsFD
from .rtsp import RtspFD
from .ism import IsmFD
from .external import FFmpegFD, get_external_downloader
from ..utils import determine_protocol

PROTOCOL_MAP = ...
def get_suitable_downloader(info_dict, params=...): # -> Any | Type[FFmpegFD] | Type[HlsFD] | Type[RtmpFD] | Type[RtspFD] | Type[F4mFD] | Type[DashSegmentsFD] | Type[IsmFD] | Type[HttpFD]:
    """Get the downloader class that can handle the info dict."""
    ...

__all__ = ['get_suitable_downloader', 'FileDownloader']
