"""
This type stub file was generated by pyright.
"""

from .fragment import FragmentFD

class DashSegmentsFD(FragmentFD):
    """
    Download segments in a DASH manifest
    """
    FD_NAME = ...
    def real_download(self, filename, info_dict):
        ...
    


