"""
This type stub file was generated by pyright.
"""

from .common import FileDownloader

class ExternalFD(FileDownloader):
    def real_download(self, filename, info_dict): # -> bool:
        ...
    
    @classmethod
    def get_basename(cls): # -> str:
        ...
    
    @property
    def exe(self):
        ...
    
    @classmethod
    def available(cls): # -> str | Literal[False]:
        ...
    
    @classmethod
    def supports(cls, info_dict): # -> bool:
        ...
    
    @classmethod
    def can_download(cls, info_dict): # -> str | bool:
        ...
    


class CurlFD(ExternalFD):
    AVAILABLE_OPT = ...


class AxelFD(ExternalFD):
    AVAILABLE_OPT = ...


class WgetFD(ExternalFD):
    AVAILABLE_OPT = ...


class Aria2cFD(ExternalFD):
    AVAILABLE_OPT = ...


class HttpieFD(ExternalFD):
    @classmethod
    def available(cls): # -> Literal[False, 'http']:
        ...
    


class FFmpegFD(ExternalFD):
    @classmethod
    def supports(cls, info_dict): # -> bool:
        ...
    
    @classmethod
    def available(cls): # -> bool:
        ...
    


class AVconvFD(FFmpegFD):
    ...


_BY_NAME = ...
def list_external_downloaders(): # -> list[Any]:
    ...

def get_external_downloader(external_downloader): # -> Any:
    """ Given the name of the executable, see whether we support the given
        downloader . """
    ...

