"""
This type stub file was generated by pyright.
"""

from .fragment import FragmentFD

class HlsFD(FragmentFD):
    """ A limited implementation that does not require ffmpeg """
    FD_NAME = ...
    @staticmethod
    def can_download(manifest, info_dict): # -> bool:
        ...
    
    def real_download(self, filename, info_dict):
        ...
    


