"""
This type stub file was generated by pyright.
"""

from .common import FileDownloader

class RtspFD(FileDownloader):
    def real_download(self, filename, info_dict): # -> bool:
        ...
    


