"""
This type stub file was generated by pyright.
"""

"""Imports all optional dependencies for the project.
An attribute "_yt_dlp__identifier" may be inserted into the module if it uses an ambiguous namespace"""
secretstorage = ...
all_dependencies = ...
available_dependencies = ...
__all__ = ['all_dependencies', 'available_dependencies', *all_dependencies.keys()]
