"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class AmericasTestKitchenIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class AmericasTestKitchenSeasonIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


