"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class NovaEmbedIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...


class NovaIE(InfoExtractor):
    IE_DESC = ...
    _VALID_URL = ...
    _TESTS = ...


