"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class SpankBangIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class SpankBangPlaylistIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...


