"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class TMZIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class TMZArticleIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...


