"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class SprutoBaseIE(InfoExtractor):
    ...


class VimpleIE(SprutoBaseIE):
    IE_DESC = ...
    _VALID_URL = ...
    _TESTS = ...


