"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class WWEBaseIE(InfoExtractor):
    _SUBTITLE_LANGS = ...


class WWEIE(WWEBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class WWEPlaylistIE(WWEBaseIE):
    _VALID_URL = ...
    _TESTS = ...
    @classmethod
    def suitable(cls, url): # -> bool:
        ...
    


