"""
This type stub file was generated by pyright.
"""

from ..utils import NO_DEFAULT, determine_protocol
from .common import FileDownloader
from .dash import DashSegmentsFD
from .external import FFmpegFD, get_external_downloader
from .f4m import F4mFD
from .fc2 import FC2LiveFD
from .hls import HlsFD
from .http import HttpFD
from .ism import IsmFD
from .mhtml import MhtmlFD
from .niconico import NiconicoDmcFD
from .rtmp import RtmpFD
from .rtsp import RtspFD
from .websocket import WebSocketFragmentFD
from .youtube_live_chat import YoutubeLiveChatFD

def get_suitable_downloader(info_dict, params=..., default=..., protocol=..., to_stdout=...): # -> Type[FFmpegFD] | Type[DashSegmentsFD] | Any | Type[HlsFD] | Type[RtmpFD] | Type[RtspFD] | Type[F4mFD] | Type[IsmFD] | Type[MhtmlFD] | Type[NiconicoDmcFD] | Type[FC2LiveFD] | Type[WebSocketFragmentFD] | Type[YoutubeLiveChatFD] | Type[HttpFD] | None:
    ...

PROTOCOL_MAP = ...
def shorten_protocol_name(proto, simplify=...): # -> str:
    ...

__all__ = ['FileDownloader', 'get_suitable_downloader', 'shorten_protocol_name']
