"""
This type stub file was generated by pyright.
"""

from .fragment import FragmentFD

class DashSegmentsFD(FragmentFD):
    """
    Download segments in a DASH manifest. External downloaders can take over
    the fragment downloads by supporting the 'dash_frag_urls' protocol
    """
    FD_NAME = ...
    def real_download(self, filename, info_dict): # -> bool | Any | tuple[Literal[True], Literal[False]] | tuple[Unknown, Literal[True]]:
        ...
    


