"""
This type stub file was generated by pyright.
"""

from .common import FileDownloader

class FC2LiveFD(FileDownloader):
    """
    Downloads FC2 live without being stopped. <br>
    Note, this is not a part of public API, and will be removed without notice.
    DO NOT USE
    """
    def real_download(self, filename, info_dict): # -> tuple[Literal[True], Literal[False]] | tuple[Unknown, Literal[True]]:
        ...
    


