"""
This type stub file was generated by pyright.
"""

from .fragment import FragmentFD

class HlsFD(FragmentFD):
    """
    Download segments in a m3u8 manifest. External downloaders can take over
    the fragment downloads by supporting the 'm3u8_frag_urls' protocol and
    re-defining 'supports_manifest' function
    """
    FD_NAME = ...
    @staticmethod
    def can_download(manifest, info_dict, allow_unplayable_formats=...): # -> bool:
        ...
    
    def real_download(self, filename, info_dict):
        ...
    


