"""
This type stub file was generated by pyright.
"""

from .common import FileDownloader

RESPONSE_READ_EXCEPTIONS = ...
class HttpFD(FileDownloader):
    def real_download(self, filename, info_dict): # -> bool:
        class DownloadContext(dict):
            ...
        
        
        class SucceedDownload(Exception):
            ...
        
        
        class RetryDownload(Exception):
            ...
        
        
        class NextFragment(Exception):
            ...
        
        
    


