"""
This type stub file was generated by pyright.
"""

from .fragment import FragmentFD

class MhtmlFD(FragmentFD):
    _STYLESHEET = ...
    _STYLESHEET = ...
    _STYLESHEET = ...
    def real_download(self, filename, info_dict): # -> bool:
        ...
    


