"""
This type stub file was generated by pyright.
"""

from .fragment import FragmentFD

class YoutubeLiveChatFD(FragmentFD):
    """ Downloads YouTube live chats fragment by fragment """
    def real_download(self, filename, info_dict): # -> bool:
        ...
    
    @staticmethod
    def parse_live_timestamp(action): # -> int | None:
        ...
    


