"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class BitChuteIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class BitChuteChannelIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...
    _TOKEN = ...


