"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class CamdemyIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class CamdemyFolderIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


