"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class CarambaTVIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class CarambaTVPageIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...


