"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class CNBCIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...


class CNBCVideoIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...


