"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class CondeNastIE(InfoExtractor):
    """
    Condé Nast is a media group, some of its sites use a custom HTML5 player
    that works the same in all of them.
    """
    _SITES = ...
    _VALID_URL = ...
    IE_DESC = ...
    EMBED_URL = ...
    _TESTS = ...


