"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class DLiveVODIE(InfoExtractor):
    IE_NAME = ...
    _VALID_URL = ...
    _TESTS = ...


class DLiveStreamIE(InfoExtractor):
    IE_NAME = ...
    _VALID_URL = ...


