"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class EllenTubeBaseIE(InfoExtractor):
    ...


class EllenTubeIE(EllenTubeBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class EllenTubeVideoIE(EllenTubeBaseIE):
    _VALID_URL = ...
    _TEST = ...


class EllenTubePlaylistIE(EllenTubeBaseIE):
    _VALID_URL = ...
    _TESTS = ...


