"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class FOX9IE(InfoExtractor):
    _VALID_URL = ...


class FOX9NewsIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...


