"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class HungamaIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class HungamaSongIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...


