"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor
from .arkena import ArkenaIE

class LcpPlayIE(ArkenaIE):
    _VALID_URL = ...
    _TESTS = ...


class LcpIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


