"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class MotherlessIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class MotherlessGroupIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...
    @classmethod
    def suitable(cls, url): # -> bool:
        ...
    


