"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class NexxIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class NexxEmbedIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


