"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class OnceIE(InfoExtractor):
    _VALID_URL = ...
    ADAPTIVE_URL_TEMPLATE = ...
    PROGRESSIVE_URL_TEMPLATE = ...


