"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class PicartoIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...
    @classmethod
    def suitable(cls, url): # -> bool:
        ...
    


class PicartoVodIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


