"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class R7IE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class R7ArticleIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...
    @classmethod
    def suitable(cls, url): # -> bool:
        ...
    


