"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class RedditIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...


class RedditRIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


