"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class RENTVIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class RENTVArticleIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


