"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class SeznamZpravyIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class SeznamZpravyArticleIE(InfoExtractor):
    _VALID_URL = ...
    _API_URL = ...
    _TESTS = ...


