"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class TikTokBaseIE(InfoExtractor):
    ...


class TikTokIE(TikTokBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class TikTokUserIE(TikTokBaseIE):
    _VALID_URL = ...
    _TESTS = ...
    _WORKING = ...
    @classmethod
    def suitable(cls, url): # -> bool:
        ...
    


