"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class TV2DKIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class TV2DKBornholmPlayIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...


