"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class TVANouvellesIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...
    BRIGHTCOVE_URL_TEMPLATE = ...


class TVANouvellesArticleIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...
    @classmethod
    def suitable(cls, url): # -> bool:
        ...
    


