"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class VideaIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...
    _STATIC_SECRET = ...
    @staticmethod
    def rc4(cipher_text, key): # -> str:
        ...
    


