"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class WeiboIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...


class WeiboMobileIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...


