"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class XTubeIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class XTubeUserIE(InfoExtractor):
    IE_DESC = ...
    _VALID_URL = ...
    _TEST = ...


