"""
This type stub file was generated by pyright.
"""

def rsa_verify(message, signature, key): # -> bool:
    ...

def update_self(to_screen, verbose, opener):
    """Update the program file with the latest version from the repository"""
    ...

def get_notes(versions, fromVersion): # -> list[Unknown]:
    ...

def print_notes(to_screen, versions, fromVersion=...): # -> None:
    ...

