"""
This type stub file was generated by pyright.
"""

from __future__ import unicode_literals

def gen_extractor_classes(): # -> list[Any]:
    """ Return a list of supported extractors.
    The order does matter; the first extractor matched is the one handling the URL.
    """
    ...

def gen_extractors(): # -> list[Unknown | Any]:
    """ Return a list of an instance of every supported extractor.
    The order does matter; the first extractor matched is the one handling the URL.
    """
    ...

def list_extractors(age_limit): # -> list[Unknown]:
    """
    Return a list of extractors that are suitable for the given age,
    sorted by extractor ID.
    """
    ...

def get_info_extractor(ie_name): # -> Any:
    """Returns the info extractor class with the given ie_name"""
    ...

