"""
This type stub file was generated by pyright.
"""

from .anvato import AnvatoIE

class CBSLocalIE(AnvatoIE):
    _VALID_URL_BASE = ...
    _VALID_URL = ...
    _TESTS = ...


class CBSLocalArticleIE(AnvatoIE):
    _VALID_URL = ...
    _TESTS = ...


