"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class DiscoveryGoBaseIE(InfoExtractor):
    _VALID_URL_TEMPLATE = ...


class DiscoveryGoIE(DiscoveryGoBaseIE):
    _VALID_URL = ...
    _GEO_COUNTRIES = ...
    _TEST = ...


class DiscoveryGoPlaylistIE(DiscoveryGoBaseIE):
    _VALID_URL = ...
    _TEST = ...
    @classmethod
    def suitable(cls, url): # -> bool:
        ...
    


