"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class HBOBaseIE(InfoExtractor):
    _FORMATS_INFO = ...


class HBOIE(HBOBaseIE):
    IE_NAME = ...
    _VALID_URL = ...
    _TEST = ...


