"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class NewgroundsIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class NewgroundsPlaylistIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


