"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class RMCDecouverteIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...
    BRIGHTCOVE_URL_TEMPLATE = ...


