"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class StitcherBaseIE(InfoExtractor):
    _VALID_URL_BASE = ...


class StitcherIE(StitcherBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class StitcherShowIE(StitcherBaseIE):
    _VALID_URL = ...
    _TESTS = ...


