"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class TrovoBaseIE(InfoExtractor):
    _VALID_URL_BASE = ...


class TrovoIE(TrovoBaseIE):
    _VALID_URL = ...


class TrovoVodIE(TrovoBaseIE):
    _VALID_URL = ...
    _TESTS = ...


