"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class TVNowBaseIE(InfoExtractor):
    _VIDEO_FIELDS = ...


class TVNowIE(TVNowBaseIE):
    _VALID_URL = ...
    @classmethod
    def suitable(cls, url): # -> bool:
        ...
    
    _TESTS = ...


class TVNowNewIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class TVNowNewBaseIE(InfoExtractor):
    ...


class TVNowListBaseIE(TVNowNewBaseIE):
    _SHOW_VALID_URL = ...
    @classmethod
    def suitable(cls, url): # -> bool:
        ...
    


class TVNowSeasonIE(TVNowListBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class TVNowAnnualIE(TVNowListBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class TVNowShowIE(TVNowListBaseIE):
    _VALID_URL = ...
    _TESTS = ...
    @classmethod
    def suitable(cls, url): # -> bool:
        ...
    


