"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor
from .once import OnceIE

class VoxMediaVolumeIE(OnceIE):
    _VALID_URL = ...


class VoxMediaIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


