"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class WebcasterIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class WebcasterFeedIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...


