"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class WSJIE(InfoExtractor):
    _VALID_URL = ...
    IE_DESC = ...
    _TESTS = ...


class WSJArticleIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...


