"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class AcFunVideoBaseIE(InfoExtractor):
    ...


class AcFunVideoIE(AcFunVideoBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class AcFunBangumiIE(AcFunVideoBaseIE):
    _VALID_URL = ...
    _TESTS = ...


