"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class Alsace20TVBaseIE(InfoExtractor):
    ...


class Alsace20TVIE(Alsace20TVBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class Alsace20TVEmbedIE(Alsace20TVBaseIE):
    _VALID_URL = ...
    _TESTS = ...


