"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor
from .amp import AMPIE

class BleacherReportIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class BleacherReportCMSIE(AMPIE):
    _VALID_URL = ...
    _TESTS = ...


