"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class BokeCCBaseIE(InfoExtractor):
    ...


class BokeCCIE(BokeCCBaseIE):
    _IE_DESC = ...
    _VALID_URL = ...
    _TESTS = ...


