"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class BooyahBaseIE(InfoExtractor):
    _BOOYAH_SESSION_KEY = ...


class BooyahClipsIE(BooyahBaseIE):
    _VALID_URL = ...
    _TESTS = ...


