"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class CallinIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...
    def try_get_user_name(self, d): # -> LiteralString:
        ...
    


