"""
This type stub file was generated by pyright.
"""

from .theplatform import ThePlatformFeedIE

class CBSBaseIE(ThePlatformFeedIE):
    ...


class CBSIE(CBSBaseIE):
    _VALID_URL = ...
    _TESTS = ...


