"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class ChingariBaseIE(InfoExtractor):
    ...


class ChingariIE(ChingariBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class ChingariUserIE(ChingariBaseIE):
    _VALID_URL = ...
    _TESTS = ...


