"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class CrowdBunkerIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class CrowdBunkerChannelIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


