"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class DailyWireBaseIE(InfoExtractor):
    _JSON_PATH = ...


class DailyWireIE(DailyWireBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class DailyWirePodcastIE(DailyWireBaseIE):
    _VALID_URL = ...
    _TESTS = ...


