"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class DeezerBaseInfoExtractor(InfoExtractor):
    def get_data(self, url): # -> tuple[Unknown, Unknown | Any, Any]:
        ...
    


class DeezerPlaylistIE(DeezerBaseInfoExtractor):
    _VALID_URL = ...
    _TEST = ...


class DeezerAlbumIE(DeezerBaseInfoExtractor):
    _VALID_URL = ...
    _TEST = ...


