"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class DeuxMIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class DeuxMNewsIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


