"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class DouyuTVIE(InfoExtractor):
    IE_DESC = ...
    _VALID_URL = ...
    _TESTS = ...


class DouyuShowIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


