"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class EaglePlatformIE(InfoExtractor):
    _VALID_URL = ...
    _EMBED_REGEX = ...
    _TESTS = ...


class ClipYouEmbedIE(InfoExtractor):
    _VALID_URL = ...


