"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class EpiconIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class EpiconSeriesIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


