"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class FreeTvBaseIE(InfoExtractor):
    ...


class FreeTvMoviesIE(FreeTvBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class FreeTvIE(FreeTvBaseIE):
    IE_NAME = ...
    _VALID_URL = ...
    _TESTS = ...


