"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class GabTVIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class GabIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


