"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class GeniusIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class GeniusLyricsIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


