"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class GettrBaseIE(InfoExtractor):
    _BASE_REGEX = ...
    _MEDIA_BASE_URL = ...


class GettrIE(GettrBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class GettrStreamingIE(GettrBaseIE):
    _VALID_URL = ...
    _TESTS = ...


