"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor
from ..utils import ExtractorError

class GoPlayIE(InfoExtractor):
    _VALID_URL = ...
    _NETRC_MACHINE = ...
    _TESTS = ...
    _id_token = ...


class InvalidLoginException(ExtractorError):
    """ The login credentials are invalid """
    ...


class AuthenticationException(ExtractorError):
    """ Something went wrong while logging in """
    ...


class AwsIdp:
    """ AWS Identity Provider """
    def __init__(self, ie, pool_id, client_id) -> None:
        """
        :param InfoExtrator ie: The extractor that instantiated this class.
        :param str pool_id:     The AWS user pool to connect to (format: <region>_<poolid>).
                                E.g.: eu-west-1_aLkOfYN3T
        :param str client_id:   The client application ID (the ID of the application connecting)
        """
        ...
    
    def authenticate(self, username, password): # -> tuple[Unknown, Unknown]:
        """ Authenticate with a username and password. """
        ...
    
    def __str__(self) -> str:
        ...
    


