"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class IslamChannelIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class IslamChannelSeriesIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


