"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class ITProTVBaseIE(InfoExtractor):
    _ENDPOINTS = ...


class ITProTVIE(ITProTVBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class ITProTVCourseIE(ITProTVBaseIE):
    _VALID_URL = ...
    _TESTS = ...


