"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class JableIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class JablePlaylistIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


