"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class JamendoIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class JamendoAlbumIE(JamendoIE):
    _VALID_URL = ...
    _TESTS = ...


