"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class LineLiveBaseIE(InfoExtractor):
    _API_BASE_URL = ...


class LineLiveIE(LineLiveBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class LineLiveChannelIE(LineLiveBaseIE):
    _VALID_URL = ...
    _TEST = ...


