"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class LRTBaseIE(InfoExtractor):
    ...


class LRTStreamIE(LRTBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class LRTVODIE(LRTBaseIE):
    _VALID_URL = ...
    _TESTS = ...


