"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class MirrativBaseIE(InfoExtractor):
    def assert_error(self, response): # -> None:
        ...
    


class MirrativIE(MirrativBaseIE):
    IE_NAME = ...
    _VALID_URL = ...
    TESTS = ...


class MirrativUserIE(MirrativBaseIE):
    IE_NAME = ...
    _VALID_URL = ...
    _TESTS = ...


