"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor
from .keezmovies import KeezMoviesIE

class MofosexIE(KeezMoviesIE):
    _VALID_URL = ...
    _TESTS = ...


class MofosexEmbedIE(InfoExtractor):
    _VALID_URL = ...
    _EMBED_REGEX = ...
    _TESTS = ...


