"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class MwaveIE(InfoExtractor):
    _VALID_URL = ...
    _URL_TEMPLATE = ...
    _TESTS = ...


class MwaveMeetGreetIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


