"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor
from .vimple import SprutoBaseIE

class MyviIE(SprutoBaseIE):
    _VALID_URL = ...
    _EMBED_REGEX = ...
    _TESTS = ...


class MyviEmbedIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...
    @classmethod
    def suitable(cls, url): # -> bool:
        ...
    


