"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class N1InfoAssetIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class N1InfoIIE(InfoExtractor):
    IE_NAME = ...
    _VALID_URL = ...
    _TESTS = ...


