"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class NateIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...
    _QUALITY = ...


class NateProgramIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


