"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class NHLBaseIE(InfoExtractor):
    ...


class NHLIE(NHLBaseIE):
    IE_NAME = ...
    _VALID_URL = ...
    _CONTENT_DOMAIN = ...
    _TESTS = ...


