"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class OfTVIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class OfTVPlaylistIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


