"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor
from .cbs import CBSBaseIE

class ParamountPlusIE(CBSBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class ParamountPlusSeriesIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


