"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

def result_from_props(props, episode_id=...): # -> dict[str, Unknown | str | int | None]:
    ...

class PodbayFMIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class PodbayFMChannelIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...
    _PAGE_SIZE = ...


