"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class PokemonIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class PokemonWatchIE(InfoExtractor):
    _VALID_URL = ...
    _API_URL = ...
    _TESTS = ...


