"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class RadikoBaseIE(InfoExtractor):
    _FULL_KEY = ...


class RadikoIE(RadikoBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class RadikoRadioIE(RadikoBaseIE):
    _VALID_URL = ...
    _TESTS = ...


