"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class SovietsClosetBaseIE(InfoExtractor):
    MEDIADELIVERY_REFERER = ...
    def parse_nuxt_jsonp(self, nuxt_jsonp_url, video_id, name): # -> list[Unknown] | object | dict[Unknown, Unknown]:
        ...
    
    def video_meta(self, video_id, game_name, category_name, episode_number, stream_date): # -> dict[str, Unknown | dict[str, str] | str | int | float | bool | None]:
        ...
    


class SovietsClosetIE(SovietsClosetBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class SovietsClosetPlaylistIE(SovietsClosetBaseIE):
    _VALID_URL = ...
    _TESTS = ...


