"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class TestURLIE(InfoExtractor):
    """ Allows addressing of the test cases as test:yout.*be_1 """
    IE_DESC = ...
    _VALID_URL = ...


