"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class ThetaStreamIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class ThetaVideoIE(InfoExtractor):
    _VALID_URL = ...
    _TEST = ...


