"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class ThreeSpeakIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


class ThreeSpeakUserIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


