"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class TVCIE(InfoExtractor):
    _VALID_URL = ...
    _EMBED_REGEX = ...
    _TEST = ...


class TVCArticleIE(InfoExtractor):
    _VALID_URL = ...
    _TESTS = ...


