"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor
from ..utils import classproperty

class UnsupportedInfoExtractor(InfoExtractor):
    IE_DESC = ...
    URLS = ...
    @classproperty
    def IE_NAME(cls):
        ...
    


LF = ...
class KnownDRMIE(UnsupportedInfoExtractor):
    """Sites that are known to use DRM for all their videos

    Add to this list only if:
    * You are reasonably certain that the site uses DRM for ALL their videos
    * Multiple users have asked about this site on github/reddit/discord
    """
    URLS = ...
    _TESTS = ...


class KnownPiracyIE(UnsupportedInfoExtractor):
    """Sites that have been deemed to be piracy

    In order for this to not end up being a catalog of piracy sites,
    only sites that were once supported should be added to this list
    """
    URLS = ...
    _TESTS = ...


