"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class VevoBaseIE(InfoExtractor):
    ...


class VevoIE(VevoBaseIE):
    '''
    Accepts urls from vevo.com or in the format 'vevo:{id}'
    (currently used by MTVIE and MySpaceIE)
    '''
    _VALID_URL = ...
    _EMBED_REGEX = ...
    _TESTS = ...
    _VERSIONS = ...


class VevoPlaylistIE(VevoBaseIE):
    _VALID_URL = ...
    _TESTS = ...


