"""
This type stub file was generated by pyright.
"""

from .common import InfoExtractor

class ZDFBaseIE(InfoExtractor):
    _GEO_COUNTRIES = ...
    _QUALITIES = ...


class ZDFIE(ZDFBaseIE):
    _VALID_URL = ...
    _TESTS = ...


class ZDFChannelIE(ZDFBaseIE):
    _VALID_URL = ...
    _TESTS = ...
    @classmethod
    def suitable(cls, url): # -> bool:
        ...
    


