"""
This type stub file was generated by pyright.
"""

import os
import sys
import warnings
import xml.etree.ElementTree as etree
from ._deprecated import *
from .compat_utils import passthrough_module
from shlex import quote as compat_shlex_quote

class compat_HTMLParseError(ValueError):
    ...


class _TreeBuilder(etree.TreeBuilder):
    def doctype(self, name, pubid, system): # -> None:
        ...
    


def compat_etree_fromstring(text): # -> Element:
    ...

compat_os_name = ...
if compat_os_name == 'nt':
    def compat_shlex_quote(s):
        ...
    
else:
    ...
def compat_ord(c): # -> int:
    ...

if compat_os_name == 'nt' and sys.version_info < (3, 8):
    ...
else:
    compat_realpath = ...
if compat_os_name in ('nt', 'ce'):
    def compat_expanduser(path):
        ...
    
else:
    compat_expanduser = ...
if False:
    ...
