"""
This type stub file was generated by pyright.
"""

import types

_NO_ATTRIBUTE = ...
_Package = ...
def get_package_info(module): # -> Package:
    ...

def passthrough_module(parent, child, allowed_attributes=..., *, callback=...): # -> None:
    class PassthroughModule(types.ModuleType):
        ...
    
    

