"""
This type stub file was generated by pyright.
"""

tests = ...
def what(file=..., h=...): # -> str | None:
    """Detect format of image (Currently supports jpeg, png, webp, gif only)
    Ref: https://github.com/python/cpython/blob/3.10/Lib/imghdr.py
    """
    ...

