"""
This type stub file was generated by pyright.
"""

import sys
from shutil import *

if sys.platform.startswith('freebsd'):
    def copy2(src, dst, *args, **kwargs): # -> str:
        ...
    
    def move(*args, copy_function=..., **kwargs): # -> _PathReturn:
        ...
    
