"""
This type stub file was generated by pyright.
"""

from __future__ import unicode_literals
from .embedthumbnail import EmbedThumbnailPP
from .ffmpeg import FFmpegEmbedSubtitlePP, FFmpegExtractAudioPP, FFmpegFixupM3u8PP, FFmpegFixupM4aPP, FFmpegFixupStretchedPP, FFmpegMergerPP, FFmpegMetadataPP, FFmpegPostProcessor, FFmpegSubtitlesConvertorPP, FFmpegVideoConvertorPP
from .xattrpp import XAttrMetadataPP
from .execafterdownload import ExecAfterDownloadPP
from .metadatafromtitle import MetadataFromTitlePP

def get_postprocessor(key): # -> Any:
    ...

__all__ = ['EmbedThumbnailPP', 'ExecAfterDownloadPP', 'FFmpegEmbedSubtitlePP', 'FFmpegExtractAudioPP', 'FFmpegFixupM3u8PP', 'FFmpegFixupM4aPP', 'FFmpegFixupStretchedPP', 'FFmpegMergerPP', 'FFmpegMetadataPP', 'FFmpegPostProcessor', 'FFmpegSubtitlesConvertorPP', 'FFmpegVideoConvertorPP', 'MetadataFromTitlePP', 'XAttrMetadataPP']
