"""
This type stub file was generated by pyright.
"""

from .common import PostProcessor

class ExecAfterDownloadPP(PostProcessor):
    def __init__(self, downloader, exec_cmd) -> None:
        ...
    
    def run(self, information): # -> tuple[list[Unknown], Unknown]:
        ...
    


