"""
This type stub file was generated by pyright.
"""

from .common import PostProcessor

class XAttrMetadataPP(PostProcessor):
    def run(self, info): # -> tuple[list[Unknown], Unknown]:
        """ Set extended attributes on downloaded file (if xattr support is found). """
        ...
    


