"""
This type stub file was generated by pyright.
"""

from .common import PostProcessor
from .ffmpeg import FFmpegPostProcessor
from ..dependencies import mutagen
from ..utils import PostProcessingError

if mutagen:
    ...
class EmbedThumbnailPPError(PostProcessingError):
    ...


class EmbedThumbnailPP(FFmpegPostProcessor):
    def __init__(self, downloader=..., already_have_thumbnail=...) -> None:
        ...
    
    @PostProcessor._restrict_to(images=False)
    def run(self, info):
        ...
    


