"""
This type stub file was generated by pyright.
"""

from .common import PostProcessor
from .ffmpeg import FFmpegPostProcessor

_TINY_CHAPTER_DURATION = ...
DEFAULT_SPONSORBLOCK_CHAPTER_TITLE = ...
class ModifyChaptersPP(FFmpegPostProcessor):
    def __init__(self, downloader, remove_chapters_patterns=..., remove_sponsor_segments=..., remove_ranges=..., *, sponsorblock_chapter_title=..., force_keyframes=...) -> None:
        ...
    
    @PostProcessor._restrict_to(images=False)
    def run(self, info): # -> tuple[list[Unknown], Unknown]:
        ...
    
    def remove_chapters(self, filename, ranges_to_cut, concat_opts, force_keyframes=...): # -> str:
        ...
    


